{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "observability-stack.fullname" . }}-apps
  namespace: {{ .Values.serviceMonitor.namespace | default .Release.Namespace }}
  labels:
    {{- include "observability-stack.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- toYaml .Values.serviceMonitor.selector.matchLabels | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Values.serviceMonitor.namespace | default "applications" }}
  endpoints:
    {{- range .Values.serviceMonitor.endpoints }}
    - port: {{ .port }}
      path: {{ .path }}
      interval: {{ .interval }}
    {{- end }}
{{- end }}

